upstream php_fpm {
    server todo_app1:9000;
    server todo_app2:9000;
}

server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    # ROUTES LARAVEL
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php_fpm;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    # PROTÉGER LES FICHIERS CACHÉS
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
