name: Deploy to VMware (Private Cloud)

on:
  push:
    branches:
      - main

jobs:
  deploy-vmware:
    runs-on: [self-hosted, vmware]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on VMware (local Docker)
        run: |
          cd /home/devops/laravel-todo
          git pull origin main
          docker compose down
          docker compose up -d --build
